### ISSUE TITLE
Using a different font

### ISSUE THREAD

**Issue by Ivan-Brigidano** [piazzai/arguelles#11]
The Argüelles theme uses the professional font Alegreya. However, one might want to use a different font.
A package option for not using Alegreya would be appreciated so that the new font is applied consistently. Otherwise, the them font is still present in some texts such as the title or the header.

**Comment by piazzai** [comment]
Hi! The issue was already brought up here: #9. In that thread, you'll find a zip archive with an Alegreya-free version of the theme. That version comes with no maintenance.

For the moment I am not going to edit the package in order to remove the Alegreya dependency, but if you'd like to to do so and make a pull request, you're very welcome.

**Comment by piazzai** [comment]
The theme's latest release ([v2.5.0](https://github.com/piazzai/arguelles/releases/tag/v2.5.0)) can bypass Alegreya through the `noalegre` option. When this is set, Alegreya is not loaded and the theme uses beamer's default fonts, which can be overridden as usual.
