### ISSUE TITLE
Undefined control sequence \event{}

### ISSUE THREAD

**Issue by hb20007** [piazzai/arguelles#12]
I am trying to use this theme. I already have it installed through texlive and I have the correct files here: `C:\texlive\2022\texmf-dist\tex\latex\beamertheme-arguelles`. However, when trying to run `pdflatex` on the example `.tex` file, I get the following error:

```
! Undefined control sequence.
l.12 \event
           {}
?
! Emergency stop.
l.12
```

I wasn't able to figure out which package the `\event{}` control sequence is a part of, but it seems to be a more general problem as the same issue happens with `\date{}` etc. if I try to comment out `\event{}`.

**Comment by piazzai** [comment]
Hi. I've been trying to reproduce the error you're getting but to no avail. For me, the `demo.tex` file compiles correctly. The `event` command is defined internally by the theme, so the fact that it throws an undefined control sequence error seems to suggest the theme is not loading. But the `date` command is defined by the beamer class! If that throws an undefined control sequence error as well, the problem might not be with the theme.

At first sight, there seems to be an issue with your texlive installation. Unfortunately I cannot offer more guidance than this because I cannot reproduce the error. Perhaps one thing worth trying is downloading the style files from the repo and seeing if the `demo.tex` file compiles when you're loading the theme locally instead of through texlive.

**Comment by hb20007** [comment]
Hi @piazzai I checked again and actually the issue happens with `\email{}` and not `\date{}` if I comment out `\event{}`.

Since you mentioned that `\{event}` is defined internally, I tried to compare the files that I have with the ones in the repository. I see that I have `v1.2.1`, which is quite old. Looking through the repository, I see that `\event{}` was added 2 years ago (https://github.com/piazzai/arguelles/commit/83314989d2f5b03e05f56484eb24260cd56466e0). Given that I have TeX Live 2022, this explains why it's undefined for me.

I will update my TeX Live installation and it should fix this. Thank you!
