### ISSUE TITLE
Issue with multiple Sections in headline

### ISSUE THREAD

**Issue by Yaeziel** [piazzai/arguelles#4]
If I have two \Section{}, everything works fine. But when I put a third one, it appears on the top right along with the second one (which is on the top left) for all frames belonging to Sections 2 & 3. Section 1 continues to appear correctly, on its own, on the top left for its frames. Further sections (more than 3) also get added/stuck. A fourth section would go to the top right, making the third one go to the middle.

You can check it by putting two extra Sections after the \End of the Demo section.

If I'm making any mistakes here let me know. I'm not a very experienced LaTeX user, and this is the first issue I'm posting on GitHub, so I'm not sure if I'm doing things correctly.

Some pictures:

First Section:
![image](https://user-images.githubusercontent.com/13680365/226149347-c5af9b4c-c73d-44d5-a7ba-fc96c430511f.png)

Second, Third, Fourth Sections:
![image](https://user-images.githubusercontent.com/13680365/226149374-a3d34d66-bd4d-4e98-8320-502b86b94769.png)
(this appears for all frames in these 3 sections)

**Comment by piazzai** [comment]
Hi! Thanks for reporting this.

I am not sure I understand your problem, but my guess is it relates to how you are using the `\End` command. This command is supposed to figure at the end of your presentation, not at the end of a section. Its only purpose is to hide the thank-you slide (if you want to have one) from showing up in the navigation.

So instead of doing something like this:

```
\begin{document}

\Section{Introduction - Magnetic Monopoles}
\frame{}

\End

\Section{Geometric Frustration}
\frame{}
\frame{}
\frame{}
\frame{}

\Section{Spin Ice}
\frame{}
\frame{}
\frame{}

\Section{Bibliography}
\frame{}
\frame{}

\end{document}
```

You should be doing this:

```

\begin{document}

\Section{Introduction - Magnetic Monopoles}
\frame{}

\Section{Geometric Frustration}
\frame{}
\frame{}
\frame{}
\frame{}

\Section{Spin Ice}
\frame{}
\frame{}
\frame{}

\Section{Bibliography}
\frame{}
\frame{}

\End

\end{document}
```

All four sections will then line up in the navigation bar. This is the intended usage. If you add new frames or section after `\End` things will get weird.

Please let me know if I misunderstood your issue.

**Comment by Yaeziel** [comment]
Thank you for your answer. You're right, I was making wrong use of the command \End. However, as I realized in the process, what I actually wanted was only the current section appearing in the headline navigation bar.  This turned out to be a bit hard to realize, but I eventually found out that it is possible to "hack it in" via this post: 

https://tex.stackexchange.com/questions/23151/beamer-infolines-outer-theme-with-miniframe-bullets-only-for-the-current-section

This worked for me and now only the current section appears in the navigation bar, just like in the first image of my initial post. Perhaps you could add it as an option

**Comment by piazzai** [comment]
Done! You can now implement that solution by loading the theme with the `splitnav` option.
