### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by dvmorenor** [piazzai/arguelles#5]
Hi, thanks for your template, it's possible change black color of the first page?

**Comment by piazzai** [comment]
Hi! In order to do that, you're going to have to install the theme locally using the `texmf` folder method (as explained [here](https://github.com/piazzai/arguelles#installation)). Once you have the package in that folder, you can open `beamerthemecolorthemeArguelles.sty`, and you will see the following lines:

```
% color scheme
\setbeamercolor*{structure}{bg=oc-gray-0,fg=oc-gray-9}
\setbeamercolor*{background canvas}{bg=structure.fg}
\setbeamercolor*{section in head/foot}{bg=structure.fg,fg=structure.bg}
\setbeamercolor*{normal text}{fg=oc-gray-8}
\setbeamercolor*{inverted text}{fg=oc-gray-0}
\setbeamercolor*{alerted text}{fg=oc-red-9}
```

These lines set the color scheme of the theme using color definitions from the [opencolor](https://ctan.org/pkg/opencolor) package. You can modify them to change the color of the theme as you wish. If you have any trouble, let me know exactly what you're trying to do and I'll see if I can help.

**Comment by piazzai** [comment]
In response to another issue (#6), I added a new feature to the theme that provides an alternative way to achieve what you want, much simpler than the solution I provided above. You can now just place an image of the color you want in your presentation's folder, and use it as the background image of the title slide using the new `bg` frame option.

To make things simple, you can use [placehold.co](https://placehold.co/) to generate the image of the color you want. For example, suppose you want a background of the color `#1864ab`. You'll find an automatically generated square image of this color at the following link: [https://placehold.co/1000/1864ab/png?text=\n](https://placehold.co/1000/1864ab/png?text=\n). I set the size to 1000 px and the format to PNG for this example but you can change these settings directly in the url, if you want. Save the image to the folder of your presentation with a name like `example.png`.

You can then change the background color of your title slide using the `bg` frame option:

```tex
\frame[plain,bg=example.png]{\titlepage}
```
