### ISSUE TITLE
Issue with Background Images in Arguelles Theme Slides

### ISSUE THREAD

**Issue by Petesuchos** [piazzai/arguelles#6]
Hi ,

First off, I want to give you a huge shoutout for creating the Arguelles theme. It's been fantastic to work with, and I truly appreciate the effort you've put into it. 

However, I've stumbled upon a tiny hiccup that I thought I'd share. I've been trying to set background images for my slides, and while everything is smooth sailing for the title slide, the other slides seem a tad bit stubborn. They just won't show their background images! 

Here's a small snippet I whipped up to showcase what I mean:

```latex
\documentclass[aspectratio=169]{beamer}

\usetheme{Arguelles}

\title{Background Image in Arguelles}
\subtitle{Test of background image}

\begin{document}

	\usebackgroundtemplate{ \includegraphics[width=\paperwidth,height=\paperheight]{treedark.png} }
	\frame{\titlepage}
	\usebackgroundtemplate{}
	
	\usebackgroundtemplate{ \includegraphics[width=\paperwidth,height=\paperheight]{tree3.png} }
	\begin{frame}
		\frametitle{Background, where art thou?}
		\begin{itemize}
			\item The elusive background image 
		\end{itemize}
	\end{frame}
	
\end{document}
```

So, the title slide is flaunting its `treedark.png` background perfectly, but the next slide seems to be having a day off and isn't displaying its `tree3.png` background. Maybe I'm missing something obvious, or perhaps it's a tiny quirk in the theme? 

If you have any tips or tricks up your sleeve to fix this, I'd be super grateful. 

Thanks once again for your brilliant work on the theme. Looking forward to hearing from you when you get a chance!

Cheers,
Thelmo

**Comment by piazzai** [comment]
Hi Thelmo! Great to know the theme is useful to you.

The solution you tried interferes with how the theme sets the default background for your slides. To allow what you want, I created a new `bg` option you can use on frames. You have to pass the path to the background image.

Here is your snippet adapted:

```tex
\documentclass[aspectratio=169]{beamer}

\usetheme{Arguelles}

\title{Background Image in Arguelles}
\subtitle{Test of background image}

\begin{document}

\begin{frame}[plain,bg=treedark.png]
    \maketitle
\end{frame}

\begin{frame}[bg=tree3.png]
    \frametitle{Background, where art thou?}
    \begin{itemize}
        \item The elusive background image
    \end{itemize}
\end{frame}

\end{document}
```

If you want to use the same background in multiple slides without setting the option each time, you can create a new environment.

```tex
\newenvironment{bgframe}{\begin{frame}[bg=tree3.png]}{\end{frame}}
```

You will then be able to use this instead of the usual frame:

```tex
\begin{bgframe}
    \frametitle{Background, where art thou?}
    \begin{itemize}
        \item The elusive background image
    \end{itemize}
\end{bgframe}
```

To use this new feature, you will have to download the theme from GitHub. I will add it to the next release, but it will take a while for the new release to be available via the CTAN distribution network.

Hope this helps!
