### ISSUE TITLE
Display "table of contents"

### ISSUE THREAD

**Issue by nlpist** [piazzai/arguelles#7]
Dear @piazzai ,
Thank you very much for your contribution, I really like using this template.

However, I struggle with outputting the **table of content**. What do you recommend to use in order to output the table of content?

The usual `\frame{\tableofcontents}` just lists the sections in the header and doesn't look like a table of content.

Thank you.

**Comment by piazzai** [comment]
Hi @nlpist. Thanks for your interest in the theme!

I had not thought about a table of contents, because the header with section titles and bubbles for the individual frames is already a table of contents, complete with hyperlinks, and you have it on every slide. So the first question that comes to mind is: what is the reason why you want a table of contents? I am asking this because better understanding your needs will help me suggest a solution.

A possible route could be to redefine the `\tableofcontents` command so that it displays the TOC exactly as you want it. Another route, certainly much quicker, is to manually write a table of contents the way you would expect `\tableofcontents` to generate it. For example:

```
\begin{itemize}
\item Section 1
  \begin{itemize}
  \item Subsection 1.1
  \item Subsection 1.2
  \end{itemize}
\item Section 2
  \begin{itemize}
  \item Subsection 2.1
  \end{itemize}
\item Section 3
  \begin{itemize}
  \item Subsection 3.1
  \item Subsection 3.2
  \item Subsection 3.3
  \end{itemize}
\end{itemize}
```

The downside of course is that the TOC does not update automatically. However, it might still be a better solution than fiddling with the `\tableofcontents` command.
