### ISSUE TITLE
Make the package not dependent on alegreya package

### ISSUE THREAD

**Issue by nplatis** [piazzai/arguelles#9]
If one uses xelatex or lualatex and already has the Alegreya font installed system-wise, then they would not need the alegreya tex package to use the Arguelles theme. Most importantly, installing the alegreya tex package in this case would lead to having the font in two different places, which is really not a good idea.

I believe that, instead of forcing the use of this font via the package, it would be better to provide concrete instructions in the README.md file for using it via specific Beamer commands for the various tex engines.

**Comment by piazzai** [comment]
Hello! I see your point but I have a few remarks. In order of importance:

1. As far as I am aware, the theme's dependency on the Alegreya package does not cause the font to be in two different places on your system. In fact, the Alegreya package is already part of your TeX distribution, so you have it regardless of whether the theme uses it or not. And if it uses it, it does not make another copy of it.
2. Alegreya is a core aesthetic feature of the theme. I do not want to support the use of just about any font: if people want to use something ludicrous in a presentation, say, the sans-serif version of Computer Modern, they will do it without my help. That said, the use of Alegreya is not forced in any way. You are free to load another font package in your own TeX file and override the theme's default.
3. You are proposing an approach that would be convenient to users who (a) prefer XeLaTeX/LuaLaTeX, and (b) already have the Alegreya font installed system-wide. This seems a rather small group of users, especially because Alegreya is not a system font on any operating system I know. I am not sure if the specific needs of this group of users should drive design choices. Still, I am interested in making the theme more usable to this group: what would be needed exactly? An alternative code that does not load the Alegreya package but uses fontspec?

I'd be happy to know what you think.

**Comment by nplatis** [comment]
Thank you for your immediate answer.

I agree that I may be part of a _small_ minority :) I choose a minimal TeXLive install and then add packages as needed, and I already have the Alegreya font on my system.

Regarding (1), what I meant about having the font in two places is that, if you have installed it system-wise (so that your other applications can use it) **and** installed the relevant tex package, you will have the otf or ttf files in both your system font directory and in your TeX tree (the alegreya tex package comes with them). This may cause trouble because it is not clear which of the two copies is used by xelatex or lualatex.

Regarding (2), my issue is only about not being forced to _install_ the alegreya tex package to use the theme, which at the moment is impossible. Changing the font (which might have been necessary if, for example, it did not support my language) is indeed possible.

Regarding (3), one way to cater for this minority would be to avoid loading the alegreya package and use fontspec commands directly if the font can be found (fontspec has a command to check if a font exists; they say it may be rather slow, I could help test). 

As I mentioned in the first comment, I would probably prefer to not "force" any font on the theme, but this is a personal preference.

**Comment by piazzai** [comment]
Thanks a lot for replying. If I understand correctly, you would be well served by an option that causes the theme to skip loading the Alegreya package, so that the font may be used via fontspec.

It is also possible to code what the system should do if the option is used, like actually loading fontspec or checking if a font is installed, but I am not an expert on fontspec and I have no idea how it might interact with other things. Therefore, I'd be more inclined to just skip Alegreya and leave the rest up to the user. Would this work in your case?

As a side note, if you know fontspec well enough to write up the commands that should be used to load Alegreya that way, you're more than welcome to make a pull request. I would rather not endorse any other font, but allowing the same font to be loaded in different ways sounds great.

**Comment by nplatis** [comment]
Providing an option to skip loading the alegreya font package would serve
all purposes: using it via fontspec or using another font altogether. So,
this would be a very good solution!

As for providing a pull request as you suggest, I could try though I do not
feel confident enough in writing LaTeX packages. This would not be very
soon due to other commitments.

**Comment by piazzai** [comment]
Hi. I've given it a try but realized that Alegreya is too important for the theme to work well, and not loading it by default requires changes to many definitions of the theme's elements.

For example, the title page uses Alegreya package commands:
```tex
\setbeamerfont{title}{series=\AlegreyaSansBlack,size=\LARGE}
\setbeamerfont{subtitle}{series=\AlegreyaSansMedium,size=\Large}
```
As does the navigation bar:
```tex
\setbeamerfont{headline section}{series=\AlegreyaSans\scshape}
\setbeamerfont{footline section}{series=\AlegreyaSans\scshape,size=\footnotesize}
```
These commands are used in the definition of the `sans` option.
```tex
\if@optSans
    \usefonttheme[onlymath]{serif}
    \newcommand\mediumfont{\AlegreyaSansMedium}
\else
    \usefonttheme{serif}
    \newcommand\mediumfont{\AlegreyaMedium}
\fi
```

In light of this, it seemed to me too risky to dispense with the package, even only as an option. But I did not want to disappoint you so here is an alternative theme that does not load the Alegreya package at all.

[altarguelles.zip](https://github.com/piazzai/arguelles/files/14417539/altarguelles.zip)

You can unpack it in your `texmf/tex/latex` folder (which you can create, if it does not exist) and any tex file compiled on your system will recognize it as a valid theme. I called it altarguelles to prevent confusion, so you can use it by `\usetheme{altarguelles}`. Hope it helps.

**Comment by piazzai** [comment]
The theme's latest release ([v2.5.0](https://github.com/piazzai/arguelles/releases/tag/v2.5.0)) can bypass Alegreya through the `noalegre` option. When this is set, Alegreya is not loaded and the theme uses beamer's default fonts, which can be overridden as usual.
